global using NUnit.Framework;
global using EventBus.Base;
global using EventBus.Base.Abstraction;
global using EventBus.Factory;
global using EventBus.UnitTest.Events.EventHandlers;
global using EventBus.UnitTest.Events.Events;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
